### ISSUE TITLE
Access jobs through tunneled ports

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/plugin-docker-daemon-deployer#2]
Right now, every job runs on the individual public port, eg. 7000. Thus, the job is also accessible from the outside of the Racetrack.

Let's think of tunneling ports through SSH to reduce number of public ports.

**Comment by JosefAssadERST** [comment]
How do we propagate this to future infrastructure type plugins? Can we even do that? Maybe one option is encouraging it in the ITP development docs, but can something be designed/implemented in PUB that assumes a ssh tunnel is used to speak to jobs?

**Comment by iszulcdeepsense** [comment]
I guess that every plugin decides how to access jobs and we won't propagate this to future plugins. It can choose to host jobs "locally" as in the case of the K8s infrastructure plugin, where tunneling is not required.

**Comment by iszulcdeepsense** [comment]
but if it turns out to be a common scenario, surely we could incorporate that feature to Racetrack core.

**Comment by JosefAssadERST** [comment]
agreed, good analysis

**Comment by iszulcdeepsense** [comment]
As we discussed, WireGuard seems to be a good choice for establishing a tunnel

**Comment by JosefAssadERST** [comment]
> As we discussed, WireGuard seems to be a good choice for establishing a tunnel

You tried it and liked?

**Comment by iszulcdeepsense** [comment]
I tried it and it looks promising, though I think we're gonna need some kind of receiver at the other end of a tunnel communication. It would be risky to expect that we'll be able to manage network interfaces on a remote Linux with root permissions (or we decide it has to be done manually beforehand). Or Wireguard peer could be running in some sort of small "backdoor" container, making it possible to communicate with other jobs.
